apiVersion: v1
kind: ConfigMap
metadata:
  name: thumbor
data:
  thumbor.conf: |
    UPLOAD_ENABLED = False
    TC_AWS_REGION = 'us-west-2'
    TC_AWS_STORAGE_BUCKET = 'thumbor-waswani'
    TC_AWS_RESULT_STORAGE_BUCKET = 'thumbor-waswani'
    TC_AWS_RESULT_STORAGE_ROOT_PATH = 'result_storage'
    STORAGE = 'tc_aws.storages.s3_storage'
    UPLOAD_PHOTO_STORAGE = 'tc_aws.storages.s3_storage'
    RESULT_STORAGE = 'tc_aws.result_storages.s3_storage'
    TC_AWS_LOADER_BUCKET='thumbor-waswani'
    TC_AWS_ENABLE_HTTP_LOADER=False
    TC_AWS_ALLOWED_BUCKETS=False # List of allowed bucket to be requested
